/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVirtualTableRouteImport } from './routes/_authenticated/virtual-table'
import { Route as AuthenticatedRequestUsageRouteImport } from './routes/_authenticated/request-usage'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedJobsRouteRouteImport } from './routes/_authenticated/jobs/route'
import { Route as AuthenticatedFlowsRouteRouteImport } from './routes/_authenticated/flows/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedSettingsUserRouteImport } from './routes/_authenticated/settings/user'
import { Route as AuthenticatedJobsProcessIdRouteImport } from './routes/_authenticated/jobs/$processId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVirtualTableRoute =
  AuthenticatedVirtualTableRouteImport.update({
    id: '/virtual-table',
    path: '/virtual-table',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestUsageRoute =
  AuthenticatedRequestUsageRouteImport.update({
    id: '/request-usage',
    path: '/request-usage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRouteRoute = AuthenticatedJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlowsRouteRoute = AuthenticatedFlowsRouteRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJobsRouteRoute,
} as any)
const AuthenticatedSettingsUserRoute =
  AuthenticatedSettingsUserRouteImport.update({
    id: '/settings/user',
    path: '/settings/user',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsProcessIdRoute =
  AuthenticatedJobsProcessIdRouteImport.update({
    id: '/$processId',
    path: '/$processId',
    getParentRoute: () => AuthenticatedJobsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flows': typeof AuthenticatedFlowsRouteRoute
  '/jobs': typeof AuthenticatedJobsRouteRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/request-usage': typeof AuthenticatedRequestUsageRoute
  '/virtual-table': typeof AuthenticatedVirtualTableRoute
  '/jobs/$processId': typeof AuthenticatedJobsProcessIdRoute
  '/settings/user': typeof AuthenticatedSettingsUserRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flows': typeof AuthenticatedFlowsRouteRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/request-usage': typeof AuthenticatedRequestUsageRoute
  '/virtual-table': typeof AuthenticatedVirtualTableRoute
  '/jobs/$processId': typeof AuthenticatedJobsProcessIdRoute
  '/settings/user': typeof AuthenticatedSettingsUserRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/flows': typeof AuthenticatedFlowsRouteRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/request-usage': typeof AuthenticatedRequestUsageRoute
  '/_authenticated/virtual-table': typeof AuthenticatedVirtualTableRoute
  '/_authenticated/jobs/$processId': typeof AuthenticatedJobsProcessIdRoute
  '/_authenticated/settings/user': typeof AuthenticatedSettingsUserRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flows'
    | '/jobs'
    | '/calendar'
    | '/dashboard'
    | '/request-usage'
    | '/virtual-table'
    | '/jobs/$processId'
    | '/settings/user'
    | '/jobs/'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flows'
    | '/calendar'
    | '/dashboard'
    | '/request-usage'
    | '/virtual-table'
    | '/jobs/$processId'
    | '/settings/user'
    | '/jobs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/flows'
    | '/_authenticated/jobs'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/request-usage'
    | '/_authenticated/virtual-table'
    | '/_authenticated/jobs/$processId'
    | '/_authenticated/settings/user'
    | '/_authenticated/jobs/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/virtual-table': {
      id: '/_authenticated/virtual-table'
      path: '/virtual-table'
      fullPath: '/virtual-table'
      preLoaderRoute: typeof AuthenticatedVirtualTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/request-usage': {
      id: '/_authenticated/request-usage'
      path: '/request-usage'
      fullPath: '/request-usage'
      preLoaderRoute: typeof AuthenticatedRequestUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flows': {
      id: '/_authenticated/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AuthenticatedFlowsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedJobsRouteRoute
    }
    '/_authenticated/settings/user': {
      id: '/_authenticated/settings/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof AuthenticatedSettingsUserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$processId': {
      id: '/_authenticated/jobs/$processId'
      path: '/$processId'
      fullPath: '/jobs/$processId'
      preLoaderRoute: typeof AuthenticatedJobsProcessIdRouteImport
      parentRoute: typeof AuthenticatedJobsRouteRoute
    }
  }
}

interface AuthenticatedJobsRouteRouteChildren {
  AuthenticatedJobsProcessIdRoute: typeof AuthenticatedJobsProcessIdRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedJobsRouteRouteChildren: AuthenticatedJobsRouteRouteChildren =
  {
    AuthenticatedJobsProcessIdRoute: AuthenticatedJobsProcessIdRoute,
    AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  }

const AuthenticatedJobsRouteRouteWithChildren =
  AuthenticatedJobsRouteRoute._addFileChildren(
    AuthenticatedJobsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFlowsRouteRoute: typeof AuthenticatedFlowsRouteRoute
  AuthenticatedJobsRouteRoute: typeof AuthenticatedJobsRouteRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRequestUsageRoute: typeof AuthenticatedRequestUsageRoute
  AuthenticatedVirtualTableRoute: typeof AuthenticatedVirtualTableRoute
  AuthenticatedSettingsUserRoute: typeof AuthenticatedSettingsUserRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFlowsRouteRoute: AuthenticatedFlowsRouteRoute,
  AuthenticatedJobsRouteRoute: AuthenticatedJobsRouteRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRequestUsageRoute: AuthenticatedRequestUsageRoute,
  AuthenticatedVirtualTableRoute: AuthenticatedVirtualTableRoute,
  AuthenticatedSettingsUserRoute: AuthenticatedSettingsUserRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
